import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./queryClient";
import StyledComponentsRegistry from "./registry";
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  weight: ["400", "700"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
}
);

export const metadata: Metadata = {
  title: "Cripto Proxi",
  description: "Generated by create next app",
};

console.log("Styled-components en SSR:", typeof window === "undefined");


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <StyledComponentsRegistry>
          <QueryProvider>
            {children}
          </QueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
